// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentNullException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.DefaultSkinStore.#StoreSkin(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.IO.FileNotFoundException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.DefaultSkinStore.#StoreSkin(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "skinData", Scope = "member", Target = "Neovolve.Switch.DefaultSkinStore.#StoreSkin(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentNullException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.FileSystemSkinStore.#.ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentNullException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.FileSystemSkinStore.#StoreSkin(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.IO.FileNotFoundException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.FileSystemSkinStore.#StoreSkin(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "skinData", Scope = "member", Target = "Neovolve.Switch.FileSystemSkinStore.#StoreSkin(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentNullException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.Skin.#.ctor(System.IO.Stream)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.Skin.#.ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentNullException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.Skin.#.ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "filePath", Scope = "member", Target = "Neovolve.Switch.Skin.#.ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentNullException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.SkinSet.#.ctor(Neovolve.Switch.ISkinStore[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentNullException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.UpdateManagement.AutoUpdateManager.#.ctor(Neovolve.Switch.UpdateManagement.AutoUpdateSettings,Neovolve.Switch.UpdateManagement.AutoUpdater)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentNullException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.UpdateManagement.AutoUpdater.#.ctor(Neovolve.Switch.Extensibility.ResourceManagement.IDownloadManager,Neovolve.Switch.Extensibility.Services.ILogWriter,Neovolve.Switch.Extensibility.Services.IUserNotification,Neovolve.Switch.UpdateManagement.AutoUpdateSettings,Neovolve.Switch.UpdateManagement.IPackageInstaller)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "downloadManager", Scope = "member", Target = "Neovolve.Switch.UpdateManagement.AutoUpdater.#.ctor(Neovolve.Switch.Extensibility.ResourceManagement.IDownloadManager,Neovolve.Switch.Extensibility.Services.ILogWriter,Neovolve.Switch.Extensibility.Services.IUserNotification,Neovolve.Switch.UpdateManagement.AutoUpdateSettings,Neovolve.Switch.UpdateManagement.IPackageInstaller)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "packageInstaller", Scope = "member", Target = "Neovolve.Switch.UpdateManagement.AutoUpdater.#.ctor(Neovolve.Switch.Extensibility.ResourceManagement.IDownloadManager,Neovolve.Switch.Extensibility.Services.ILogWriter,Neovolve.Switch.Extensibility.Services.IUserNotification,Neovolve.Switch.UpdateManagement.AutoUpdateSettings,Neovolve.Switch.UpdateManagement.IPackageInstaller)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "userNotification", Scope = "member", Target = "Neovolve.Switch.UpdateManagement.AutoUpdater.#.ctor(Neovolve.Switch.Extensibility.ResourceManagement.IDownloadManager,Neovolve.Switch.Extensibility.Services.ILogWriter,Neovolve.Switch.Extensibility.Services.IUserNotification,Neovolve.Switch.UpdateManagement.AutoUpdateSettings,Neovolve.Switch.UpdateManagement.IPackageInstaller)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "logWriter", Scope = "member", Target = "Neovolve.Switch.UpdateManagement.AutoUpdater.#.ctor(Neovolve.Switch.Extensibility.ResourceManagement.IDownloadManager,Neovolve.Switch.Extensibility.Services.ILogWriter,Neovolve.Switch.Extensibility.Services.IUserNotification,Neovolve.Switch.UpdateManagement.AutoUpdateSettings,Neovolve.Switch.UpdateManagement.IPackageInstaller)")]
