// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentOutOfRangeException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#AssignHsl(Neovolve.Switch.Extensibility.ColorManagement.Hsl)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "hexColor", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#AssignHex(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentNullException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#AssignHex(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Neovolve.Switch.Extensibility.Services")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Neovolve.Switch.Extensibility.ResourceManagement")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "HslScaleDescription", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#AssignHsl(Neovolve.Switch.Extensibility.ColorManagement.Hsl)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "HueMax", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#AssignHsl(Neovolve.Switch.Extensibility.ColorManagement.Hsl)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "LuminanceMax", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#AssignHsl(Neovolve.Switch.Extensibility.ColorManagement.Hsl)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "SaturationMax", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#AssignHsl(Neovolve.Switch.Extensibility.ColorManagement.Hsl)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "hslColor", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#AssignHsl(Neovolve.Switch.Extensibility.ColorManagement.Hsl)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentOutOfRangeException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#AssignOle(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "oleColor", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#AssignOle(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentOutOfRangeException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#AssignRgb(Neovolve.Switch.Extensibility.ColorManagement.Rgb)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "rgbColor", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#AssignRgb(Neovolve.Switch.Extensibility.ColorManagement.Rgb)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Ensures(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#HexColor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "HexColor", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#HexColor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Ensures(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#HslColor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "HslColor", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#HslColor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Ensures(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#OleColor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "OleColor", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#OleColor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Ensures(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#RgbColor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "RgbColor", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.BaseColorConverter.#RgbColor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Requires<System.ArgumentNullException>(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.WindowsColorConverter.#.ctor(Neovolve.Switch.Extensibility.ColorManagement.IHslScale)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "HslScaleDescription", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.WindowsColorConverter.#HslScaleDescription")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Diagnostics.Contracts.__ContractsRuntime.Ensures(System.Boolean,System.String,System.String)", Scope = "member", Target = "Neovolve.Switch.Extensibility.ColorManagement.WindowsColorConverter.#HslScaleDescription")]
